### ISSUE TITLE
Item check doesn`t work

### ISSUE THREAD

**Issue by AlekseyVideman** [BetterGUI-MC/BetterGUI#12]
Hello! In the chestcommandsgui forked plugin I used the player's item content check:
  CLICK-REQUIREMENT:
    ITEM: 'emerald,1'
  COMMAND: 'givemoney: 100'

This doesn't work in BetterGUI, how do I use item verification in BetterGUI?

**Comment by notfoundname** [comment]
https://ci.codemc.io/view/Author/job/BetterGUI-MC/view/Addon/job/ItemGotcha/
use this addon to make it, move downloaded file to /BetterGUI/addon/

**Comment by HSGamer** [comment]
You need to install VaultBridge and ItemGotcha, which you can get from my discord.
For the item check, this is the wiki for it: https://github.com/BetterGUI-MC/ItemGotcha
You can join my discord server to get further support
