### ISSUE TITLE
Tab complete

### ISSUE THREAD

**Issue by andris155** [BetterGUI-MC/BetterGUI#17]
### **Describe the bug**
The tab complete not work with menu commands

### **To Reproduce**
1. Begin type the menu command.
2. Press tab key.
...

### **Expected behavior**
Tab complete works with menu commands

### **Version**
- Minecraft: 1.15.2
- Spigot/Bukkit: 1.15.2 Paper
- BetterGUI: 1.3

**Comment by HSGamer** [comment]
This is a known issue 
By far, the way this plugin registers commands maybe not proper, due to the usage of dynamic commands.

**Comment by HSGamer** [comment]
The issue happens in 1.13 and above
