### ISSUE TITLE
Menu open cause lag when opened first after server started

### ISSUE THREAD

**Issue by andris155** [BetterGUI-MC/BetterGUI#198]
### **Describe the bug**
* [x] Make sure you've read the wiki

### **To Reproduce**
1. Start server.
2. Open menu.

### **Expected behavior**
Menu open no cause lag when opened first after server started

### **Details**
https://pastebin.com/QRftXL5A

### **Version**
- Minecraft: 1.16.5
- Tuinity
- BetterGUI: 5.8
- Installed Addons: none

### **Additional context**
https://pastebin.com/Tghrx3dR

**Comment by HSGamer** [comment]
caused by the sync load of SkullUtils from XSeries

**Comment by andris155** [comment]
Can't this be fixed?

**Comment by HSGamer** [comment]
Try this build. It fixed your issue.
https://ci.codemc.io/job/BetterGUI-MC/job/BetterGUI/546/artifact/target/BetterGUI.jar

**Comment by andris155** [comment]
Thanks!
