### ISSUE TITLE
Menu open still cause lag when opened first after server started

### ISSUE THREAD

**Issue by andris155** [BetterGUI-MC/BetterGUI#201]
### **Describe the bug**
* [x] Make sure you've read the wiki

Maybe cause lag the menu permission calculation?

```
me.hsgamer.bettergui.lib.core.bukkit.utils.PermissionUtils.createPermission(PermissionUtils.java:36)
me.hsgamer.bettergui.Permissions.<clinit>(Permissions.java:18)
me.hsgamer.bettergui.manager.MenuCommandManager$1.execute(MenuCommandManager.java:33)
```

### **To Reproduce**
1. Restart server.
2. Open menu with menu command.
3. Causes server lag.

### **Expected behavior**

Menu open no cause lag when opened first after server started.

### **Details**
Your menu config, addon config or anything related to your problem

https://pastebin.com/YNdyUD7v

### **Version**
- Minecraft: 1.16.5
- Spigot/Bukkit/...: Tuinity
- BetterGUI: 5.9
- Installed Addons: none

### **Additional context**

https://pastebin.com/nsjMUcX1

**Comment by HSGamer** [comment]
https://ci.codemc.io/job/BetterGUI-MC/job/BetterGUI/585/artifact/target/BetterGUI.jar
