### ISSUE TITLE
Mode-display button suggestion.

### ISSUE THREAD

**Issue by fr1g** [BetterGUI-MC/BetterGUI#236]
**Is your feature request related to a problem? Please describe.**

May I ask if you already have this function? I cannot find this in the example menu. Anyway, I prefer a button can express the mode currently by using different items as icon.

**Describe the solution you'd like**

Some toggles will have hints. So if BetterGUI detected a certain hint from server, just as if it checked the toggle mode changed, then change its look-like. And in config files for every menus, can be like:

gamemode toggle:
  id: redstone_lamp | shroomlight
  command: 'gamemode creative*~%player%'s gamemode changed to Creative | ...'
  name: 'hit to switch gamemode'
  slot: xxx

The | is the sign that make the plugin know should seperate strings here, and *~ point to the server's broadcast message.
Then, a button now set-up, after one click, it will change gamemode and change its icon.

**Describe alternatives you've considered**
Alternative...just make the config easier?

**Additional context**

If it's impossible to make it come true, just close this issue and ignore me. Sorry if so.

**Comment by HSGamer** [comment]
Use `Predicate Button`
