### ISSUE TITLE
Error 1.18.2 log

### ISSUE THREAD

**Issue by lostINParadies** [BetterGUI-MC/BetterGUI#246]
https://pastebin.com/YmKudQU7

Error 1.18.2. No Crash - everything works normally

### **Version**
- Minecraft: [1.18.2]
- Paper: [1.18.2, ]  git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)

- BetterGUI 6.5
- Installed Addons: ALL

**Comment by HSGamer** [comment]
Use BetterGUI 6.6
