### ISSUE TITLE
Command sending when not suppose to

### ISSUE THREAD

**Issue by winnipeg21** [BetterGUI-MC/BetterGUI#31]
### **Describe the bug**
When you leave the open and closing messages of your menu blank it still sends a / as a command causing "Unknown Command" message to appear.

### **To Reproduce**
1. Remove Open/Close messages to a menu
2. Restart plugin
3. Open a menu or close it
...

### **Expected behavior**
There should be no message or command sent

### **Screenshots**
https://s.pingu.ga/gs94je.png

### **Version**
- Paper 1.15.2 - #162

**Comment by HSGamer** [comment]
I need your menu config.
If you just clear the open-action, wrong.
You need to remove it altogether.

**Comment by winnipeg21** [comment]
I have it removed altogether and still getting the / in the console as-well-as unknown command

https://pastebin.com/84piPjNB

**Comment by HSGamer** [comment]
Why are there 2 "menu-settings"??

**Comment by winnipeg21** [comment]
Shouldn't be? must've duplicated it before I pasted it

**Comment by HSGamer** [comment]
Yeah... it shouldn't be
And don't set the open-action and close-action to something like this
```yaml
open-action:
- ''
```
It's not for removing the commands, it runs the empty command.
If you don't need it, remove it altogether.
