### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by winnipeg21** [BetterGUI-MC/BetterGUI#32]
### **Describe the bug**
I set the requirement '{money} => 10000' and it just completely ignored it. Causing the command to be executed

### **To Reproduce**
1. Create a click-requirement with a condition of {money} => 10000
...

### **Expected behavior**
It should give a failure saying "Can't meet requirement"

### **Version**
- Paper 1.15.2

**Comment by HSGamer** [comment]
Should be {money} >= 10000

**Comment by winnipeg21** [comment]
Still ignores it sadly

**Comment by HSGamer** [comment]
Did you install VaultBridge addon from my discord??

**Comment by winnipeg21** [comment]
Never seen anywhere that you needed an addon for vault lmao

**Comment by HSGamer** [comment]
If you read the wiki, you will notice that there is no variable for Vault.
And I said that you need to join my discord server to get the addons.
