### ISSUE TITLE
Option to only allow certain clicks

### ISSUE THREAD

**Issue by winnipeg21** [BetterGUI-MC/BetterGUI#33]
**Is your feature request related to a problem? Please describe.**
It's related to an issue I have where players are able to right-click, left-click and middle-click where I only want right-click.

**Describe the solution you'd like**
Allow an option under the item name to be only-allow-click: right, left, middle, etc.. 

**Describe alternatives you've considered**
Just add an option field anywhere that allow restricting clicking/executing the commands to a certain key.

**Comment by HSGamer** [comment]
https://github.com/BetterGUI-MC/BetterGUI/wiki/Icon-Properties#click-requirement
