### ISSUE TITLE
Click Type : Sound

### ISSUE THREAD

**Issue by Command1264** [BetterGUI-MC/BetterGUI#36]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/50344708/79037865-528fea00-7c07-11ea-8762-e8772a4573e1.png)

**Describe the solution you'd like**
Hope can add this feature back

**Additional context**
![image](https://user-images.githubusercontent.com/50344708/79037815-f1681680-7c06-11ea-8dcc-f65f30710a37.png)

**Comment by HSGamer** [comment]
Join my discord server and find the NoteBlock addon from the main-addon channel.
