### ISSUE TITLE
Variables no "{money}"

### ISSUE THREAD

**Issue by Command1264** [BetterGUI-MC/BetterGUI#37]
### **Describe the bug**
Do not have "(money)" Variables

### **Screenshots**
![image](https://user-images.githubusercontent.com/50344708/79043593-aa901600-7c32-11ea-8c09-853c285f8347.png)
![image](https://user-images.githubusercontent.com/50344708/79043682-399d2e00-7c33-11ea-8bc1-eb4fb66fb3a3.png)
![image](https://user-images.githubusercontent.com/50344708/79043691-49b50d80-7c33-11ea-99fc-c70312786dbb.png)

### **Version**
- Minecraft: 1.15.2
- Spigot/Bukkit: 1.15.2
- BetterGUI: 1.9
- addons: 
  BungeeLink: 1.0
  CommandOverride: 1.1
  NBT-Support: 1.1

**Comment by HSGamer** [comment]
Join my server and find the VaultBridge addon from the main-addon channel
