### ISSUE TITLE
Command Bypass Perms

### ISSUE THREAD

**Issue by GamingInfinite** [BetterGUI-MC/BetterGUI#61]
This isn't as much a feature request as much as a, can you do it, and if you can't then it is a feature request.

I want people to be able to teleport in between worlds, but not via command.  Only by the menu.  I tried setting a perm for that (roles.builder) but because I didn't have a plugin by that name, it didn't work.  If you could tell me how to do that without having to include a plugin that would be great too.  Anyway, I tried using the multiverse teleport command itself, but that doesn't work either because then they can bypass the restrictions I'm trying to impose because the teleport command bypasses that.

**Comment by HSGamer** [comment]
The `permission:` command is what you are looking for
https://github.com/BetterGUI-MC/BetterGUI/wiki/Command-Types
